# Generated by Django 4.2.8 on 2023-12-07 15:29

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Inserção')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('job_title', models.CharField(max_length=200, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Inserção')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=50, verbose_name='Icone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Inserção')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('professional', models.CharField(max_length=100, verbose_name='Nome')),
                ('bio', models.TextField(max_length=250, verbose_name='Bio')),
                ('img', stdimage.models.StdImageField(force_min_size=False, upload_to='team', variations={'thumb': (480, 480)}, verbose_name='Imagem')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fusion.position', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
    ]
