# Generated by Django 4.2.8 on 2023-12-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='Team_Members',
        ),
    ]
