# Generated by Django 4.2.7 on 2023-11-27 18:49

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Inserção')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('stock', models.IntegerField(verbose_name='Estoque')),
                ('img', stdimage.models.StdImageField(force_min_size=False, upload_to='uploads', variations={'large': (1000, 1000), 'medium': (300, 300), 'thumb': (120, 120)}, verbose_name='Imagem')),
                ('url_slug', models.SlugField(blank=True, editable=False, max_length=250, verbose_name='Slug')),
            ],
            options={
                'db_table': 'manage_products_products',
            },
        ),
    ]
